### PR TITLE
Use a more accurate verb to express the process installing packages 

### PR DESCRIPTION
**Pull request by valentin-aleksandrov**

### CODE REVIEW

**Comment by HristoKolev** [comment]
Can you update the rest of the examples as well?

**Review by HristoKolev — CHANGES_REQUESTED** [review]
Can you update the rest of the examples as well?

**Comment by valentin-aleksandrov** [comment]
> Can you update the rest of the examples as well?

Yes, I will take care of that.

**Comment by valentin-aleksandrov** [comment]
All examples are now updated.

**Review by HristoKolev — APPROVED** [review]

**Pull request merged**
